### Check API
GET http://localhost:5001/api/attendance/Test
Content-Type: application/json

### Get Attendance
GET http://localhost:5001/api/attendance/users/{198ce3f8-b220-4e0d-bd42-4a1b7d9c6e1f}
Content-Type: application/json

### Create Attendance
POST http://localhost:5001/api/attendance/register
Content-Type: application/json

{
  "UserId": "198ce3f8-b220-4e0d-bd42-4a1b7d9c6e1f",  
  "Date": "2024-11-15T08:00:00"
}

### Delete Attendance By ID
DELETE http://localhost:5001/api/attendance/delete/{f7a100e3-7b3a-49d0-8b4b-a5043b81b0c1}
Content-Type: application/json