### Check API
GET http://localhost:5001/api/events/Test
Content-Type: application/json

### Get Event By ID
GET http://localhost:5001/api/events/{8715e7b5-e74d-4986-a1f9-2c7905c06206}
Content-Type: application/json

### Get All Events
GET http://localhost:5001/api/events/all
Content-Type: application/json

### Create a new Event
POST http://localhost:5001/api/events/create
Content-Type: application/json

{
  "Title": "Sample Event",
  "Description": "Description of the event",
  "StartTime": "2024-12-01T10:00:00",
  "EndTime": "2024-12-01T12:00:00",
  "Location": "Amsterdam",
  "Approval": true
}

### Update a Event
PUT http://localhost:5001/api/events/update
Content-Type: application/json

{
  "Id": "8715e7b5-e74d-4986-a1f9-2c7905c06206",  
  "Title": "title",
  "Description": "iets",
  "StartTime": "2024-12-01T11:00:00",
  "EndTime": "2024-12-01T13:00:00",
  "Location": "Rotterdam",
  "Approval": false
}

### Delete a Event
DELETE http://localhost:5001/api/events/delete/{5A285679-F4C0-4A16-92B2-C8371B56EA5A}
Content-Type: application/json