### Login with Correct Password
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "Email": "test@example.com",
  "Password": "password123"
}

### Login with Wrong Password
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "Email": "john.doe@example.com",
  "Password": "password122"
}

### Get User Profile (Authenticated Request)
GET http://localhost:5001/api/user/all
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

