### Check API
GET http://localhost:5001/api/shopitem/Test
Content-Type: application/json

### Get All Shop item

GET http://localhost:5001/api/shopitem/all
Content-Type: application/json

### Get Shop item by iD
GET http://localhost:5001/api/shopitem/{9fd60eb1-6a7c-4eaa-ba63-4e0ac5a4bdce}
Content-Type: application/json

### Create New Shop item
POST http://localhost:5001/api/shopitem/add
Content-Type: application/json

{
  "Price": 250,
  "Name": "DarkMode",
  "Description": "Darkmode for web pages!"
}

### Update Shop Item
PUT http://localhost:5001/api/shopitem/update/9fd60eb1-6a7c-4eaa-ba63-4e0ac5a4bdce
Content-Type: application/json

{
  "Price": 500,
  "Name": "DarkMode",
  "Description": "Darkmode for web pages!"
}

### Delete Shop Item
DELETE http://localhost:5001/api/shopitem/delete/87899a7b-0e06-4590-b70a-04e91a99acbd
Content-Type: application/json