### Test API

GET http://localhost:5001/api/users/Test
Content-Type: application/json

### Get All Users
GET http://localhost:5001/api/users/all
//Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

### Get User by ID
GET http://localhost:5001/api/users/{703fef6e-4895-41af-90ab-c88137b0126c}
//Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

Content-Type: application/json

### Create User
POST http://localhost:5001/api/users/create
Content-Type: application/json

{
  "FirstName": "Zdennick",
  "LastName": "Oosterwolde",
  "Email": "Zdennick@example.com",
  "Password": "a1b2c3d4!@",
  "RecurringDays": 7,
  "Role": 3,
  "Points": {
    "AllTimePoints": 100,
    "PointAmount": 0,
    "Items": []
  }
}

### Update User by ID 
PUT http://localhost:5001/api/users/{ef7cabc3-18df-4716-b6af-01ec4d0ede2d}
//Authorization: Bearer YOUR_ACCESS_TOKEN_HERE
Content-Type: application/json

{
  "FirstName": "Jane",
  "LastName": "Doe",
  "Email": "jane.doe@example.com",
  "Password": "newpassword123",
  "RecurringDays": 10
}

### Delete User by ID
DELETE http://localhost:5001/api/users/{ef7cabc3-18df-4716-b6af-01ec4d0ede2d}
//Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

Content-Type: application/json
